name: Post Build Action

run-name: 'Post Build Action -- ${{github.event.workflow_run.head_branch}}'

on:
   workflow_run:
    workflows:
      - Build Workflow
    types:
      - completed

permissions:
  contents: write 
        
jobs:
  post-build:
    name: Post Build Actions
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'ikmdev'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{github.event.workflow_run.head_repository.full_name}}
          ref: ${{github.event.workflow_run.head_branch}}
          fetch-depth: 0

      - name: Plugins Post Build
        id: plugins_post_build
        uses: ikmdev/maven-post-build-action@v3.2.0
        with:
          mvn_additional_args: " -f plugin -s '/home/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/.m2/settings.xml' -DrepositoryId='${{ steps.is_tag.outputs.NEXUS_REPO_ID }}'"
          nexus_repo_password: ${{secrets.EC2_NEXUS_PASSWORD}}
          branch_name: ${{github.event.workflow_run.head_branch}}
          github_token: ${{secrets.GITHUB_TOKEN}}
          maven_central_username: ${{secrets.MC_SECRET_USERNAME}}
          maven_central_password: ${{secrets.MC_SECRET_PASSWORD}}
          gpg_key: ${{secrets.GPG_KEY}}
          gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
          sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
          sonarcloud_tests: ${{ '' }}

      - name: Data Pipeline Post Build
        id: data_pipeline_post_build
        uses: ikmdev/maven-post-build-action@v3.2.0
        with:
            mvn_additional_args: " -s '/home/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/.m2/settings.xml' -DrepositoryId='${{ steps.is_tag.outputs.NEXUS_REPO_ID }}'"
            nexus_repo_password: ${{secrets.EC2_NEXUS_PASSWORD}}
            branch_name: ${{github.event.workflow_run.head_branch}}
            github_token: ${{secrets.GITHUB_TOKEN}}
            maven_central_username: ${{secrets.MC_SECRET_USERNAME}}
            maven_central_password: ${{secrets.MC_SECRET_PASSWORD}}
            gpg_key: ${{secrets.GPG_KEY}}
            gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
            sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
            sonarcloud_tests: ${{ '' }}
